-- MySQL Script generated by MySQL Workbench
-- Thu Jul 22 22:28:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS collegeDB;
CREATE DATABASE collegeDB;
USE collegeDB;
-- -----------------------------------------------------
-- Table `student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student` ;

CREATE TABLE IF NOT EXISTS `student` (
  `student_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faculty` ;

CREATE TABLE IF NOT EXISTS `faculty` (
  `faculty_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `salary` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`faculty_id`),
  UNIQUE INDEX `faculty_id_UNIQUE` (`faculty_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `advisor` ;

CREATE TABLE IF NOT EXISTS `advisor` (
  `advisor_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'Enter description of advisor',
  `faculty_id` INT NOT NULL,
  PRIMARY KEY (`advisor_id`),
  INDEX `fk_advisor_faculty_idx` (`faculty_id` ASC) VISIBLE,
  CONSTRAINT `fk_advisor_faculty`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researcher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researcher` ;

CREATE TABLE IF NOT EXISTS `researcher` (
  `researcher_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter description of researcher',
  `faculty_id` INT NOT NULL,
  PRIMARY KEY (`researcher_id`),
  UNIQUE INDEX `researcher_id_UNIQUE` (`researcher_id` ASC) VISIBLE,
  INDEX `fk_researcher_faculty_idx` (`faculty_id` ASC) VISIBLE,
  CONSTRAINT `fk_researcher_faculty`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `office` ;

CREATE TABLE IF NOT EXISTS `office` (
  `office_id` INT NOT NULL AUTO_INCREMENT,
  `room_num` CHAR(3) NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`office_id`),
  UNIQUE INDEX `office_id_UNIQUE` (`office_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lecturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecturer` ;

CREATE TABLE IF NOT EXISTS `lecturer` (
  `lecturer_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter description of lecturer',
  `faculty_id` INT NOT NULL,
  `office` INT NOT NULL,
  PRIMARY KEY (`lecturer_id`),
  UNIQUE INDEX `lecturer_id_UNIQUE` (`lecturer_id` ASC) VISIBLE,
  INDEX `fk_lecturer_faculty_idx` (`faculty_id` ASC) VISIBLE,
  INDEX `fk_lecturer_office_idx` (`office` ASC) VISIBLE,
  CONSTRAINT `fk_lecturer_faculty`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lecturer_office`
    FOREIGN KEY (`office`)
    REFERENCES `office` (`office_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `professor` ;

CREATE TABLE IF NOT EXISTS `professor` (
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter professors desciption here',
  `faculty_id` INT NOT NULL,
  `office` INT NOT NULL,
  PRIMARY KEY (`professor_id`),
  UNIQUE INDEX `professor_id_UNIQUE` (`professor_id` ASC) VISIBLE,
  INDEX `fk_professor_faculty_idx` (`faculty_id` ASC) VISIBLE,
  INDEX `fk_professor_office_idx` (`office` ASC) VISIBLE,
  CONSTRAINT `fk_professor_faculty`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_professor_office`
    FOREIGN KEY (`office`)
    REFERENCES `office` (`office_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chair` ;

CREATE TABLE IF NOT EXISTS `chair` (
  `chair_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter chair description here',
  `faculty_id` INT NOT NULL,
  `office` INT NOT NULL,
  PRIMARY KEY (`chair_id`),
  UNIQUE INDEX `chair_id_UNIQUE` (`chair_id` ASC) VISIBLE,
  INDEX `fk_chair_faculty_idx` (`faculty_id` ASC) VISIBLE,
  INDEX `fk_chair_office_idx` (`office` ASC) VISIBLE,
  CONSTRAINT `fk_chair_faculty`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chair_office`
    FOREIGN KEY (`office`)
    REFERENCES `office` (`office_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `staff` ;

CREATE TABLE IF NOT EXISTS `staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`staff_id`),
  UNIQUE INDEX `staff_id_UNIQUE` (`staff_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `custodian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custodian` ;

CREATE TABLE IF NOT EXISTS `custodian` (
  `custodian_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'custodian description',
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`custodian_id`),
  INDEX `fk_custodian_staff_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_custodian_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `librarian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `librarian` ;

CREATE TABLE IF NOT EXISTS `librarian` (
  `librarian_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter librarian description here',
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`librarian_id`),
  UNIQUE INDEX `librarian_id_UNIQUE` (`librarian_id` ASC) VISIBLE,
  INDEX `fk_librarian_staff_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_librarian_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food clerk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food clerk` ;

CREATE TABLE IF NOT EXISTS `food clerk` (
  `foodclerk_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter food clerk description here',
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`foodclerk_id`),
  UNIQUE INDEX `foodclerk_id_UNIQUE` (`foodclerk_id` ASC) VISIBLE,
  INDEX `fk_food clerk_staff_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_food clerk_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipment` ;

CREATE TABLE IF NOT EXISTS `equipment` (
  `equipment_id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(100) NOT NULL,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter equipment description',
  `staff` INT NOT NULL,
  PRIMARY KEY (`equipment_id`),
  UNIQUE INDEX `equipment_id_UNIQUE` (`equipment_id` ASC) VISIBLE,
  INDEX `fk_equipment_staff_idx` (`staff` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_staff`
    FOREIGN KEY (`staff`)
    REFERENCES `staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clubs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clubs` ;

CREATE TABLE IF NOT EXISTS `clubs` (
  `club_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `num_of_members` INT NOT NULL DEFAULT 0,
  `location` VARCHAR(100) NOT NULL,
  `website` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`club_id`),
  UNIQUE INDEX `club_id_UNIQUE` (`club_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parking lots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parking lots` ;

CREATE TABLE IF NOT EXISTS `parking lots` (
  `parkinglot_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`parkinglot_id`),
  UNIQUE INDEX `parkinglot_id_UNIQUE` (`parkinglot_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `department` ;

CREATE TABLE IF NOT EXISTS `department` (
  `department_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `office_location` VARCHAR(100) NOT NULL,
  `chair_id` INT NOT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildings` ;

CREATE TABLE IF NOT EXISTS `buildings` (
  `building_id` INT NOT NULL AUTO_INCREMENT,
  `capacity` INT NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`building_id`),
  UNIQUE INDEX `building_id_UNIQUE` (`building_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campuses` ;

CREATE TABLE IF NOT EXISTS `campuses` (
  `campuses_id` INT NOT NULL AUTO_INCREMENT,
  `roles` VARCHAR(45) NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`campuses_id`),
  UNIQUE INDEX `campuses_id_UNIQUE` (`campuses_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `subjects` ;

CREATE TABLE IF NOT EXISTS `subjects` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `total_subject_nums` INT NOT NULL,
  PRIMARY KEY (`subject_id`),
  UNIQUE INDEX `subject_id_UNIQUE` (`subject_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tutoring`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tutoring` ;

CREATE TABLE IF NOT EXISTS `tutoring` (
  `tutoring_id` INT NOT NULL AUTO_INCREMENT,
  `subject` INT NOT NULL,
  `staff_members` INT NOT NULL,
  PRIMARY KEY (`tutoring_id`),
  UNIQUE INDEX `tutoring_id_UNIQUE` (`tutoring_id` ASC) VISIBLE,
  INDEX `fk_tutoring_subject_idx` (`subject` ASC) VISIBLE,
  CONSTRAINT `fk_tutoring_subject`
    FOREIGN KEY (`subject`)
    REFERENCES `subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health and wellness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `health and wellness` ;

CREATE TABLE IF NOT EXISTS `health and wellness` (
  `health_and_wellness_id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(100) NOT NULL,
  `staff_members` INT NOT NULL,
  PRIMARY KEY (`health_and_wellness_id`),
  UNIQUE INDEX `health_and_wellness_id_UNIQUE` (`health_and_wellness_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `services` ;

CREATE TABLE IF NOT EXISTS `services` (
  `services_id` INT NOT NULL AUTO_INCREMENT,
  `staff_num` INT NOT NULL,
  `health and wellness` INT NOT NULL,
  `tutoring` INT NOT NULL,
  PRIMARY KEY (`services_id`),
  UNIQUE INDEX `services_id_UNIQUE` (`services_id` ASC) VISIBLE,
  INDEX `fk_services_healthandwell_idx` (`health and wellness` ASC) VISIBLE,
  INDEX `fk_services_tutoring_idx` (`tutoring` ASC) VISIBLE,
  CONSTRAINT `fk_services_tutoring`
    FOREIGN KEY (`tutoring`)
    REFERENCES `tutoring` (`tutoring_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_services_healthandwell`
    FOREIGN KEY (`health and wellness`)
    REFERENCES `health and wellness` (`health_and_wellness_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `degrees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `degrees` ;

CREATE TABLE IF NOT EXISTS `degrees` (
  `degree_id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(25) NOT NULL,
  `type` VARCHAR(25) NOT NULL,
  `description` VARCHAR(100) NOT NULL DEFAULT 'enter degree description',
  PRIMARY KEY (`degree_id`),
  UNIQUE INDEX `degree_id_UNIQUE` (`degree_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arts` ;

CREATE TABLE IF NOT EXISTS `arts` (
  `arts_id` INT NOT NULL AUTO_INCREMENT,
  `arts_subject_num` INT NOT NULL,
  `subject` INT NOT NULL,
  PRIMARY KEY (`arts_id`),
  UNIQUE INDEX `arts_id_UNIQUE` (`arts_id` ASC) VISIBLE,
  INDEX `fk_arts_subject_idx` (`subject` ASC) VISIBLE,
  CONSTRAINT `fk_arts_subject`
    FOREIGN KEY (`subject`)
    REFERENCES `subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sciences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sciences` ;

CREATE TABLE IF NOT EXISTS `sciences` (
  `sciences_id` INT NOT NULL AUTO_INCREMENT,
  `sciences_subject_num` INT NOT NULL,
  `subject` INT NOT NULL,
  PRIMARY KEY (`sciences_id`),
  UNIQUE INDEX `sciences_id_UNIQUE` (`sciences_id` ASC) VISIBLE,
  INDEX `fk_sciences_subject_idx` (`subject` ASC) VISIBLE,
  CONSTRAINT `fk_sciences_subject`
    FOREIGN KEY (`subject`)
    REFERENCES `subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `languages` ;

CREATE TABLE IF NOT EXISTS `languages` (
  `languages_id` INT NOT NULL AUTO_INCREMENT,
  `languages_subject_num` INT NOT NULL,
  `subject` INT NOT NULL,
  PRIMARY KEY (`languages_id`),
  UNIQUE INDEX `languages_id_UNIQUE` (`languages_id` ASC) VISIBLE,
  INDEX `fk_languages_subject_idx` (`subject` ASC) VISIBLE,
  CONSTRAINT `fk_languages_subject`
    FOREIGN KEY (`subject`)
    REFERENCES `subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course` ;

CREATE TABLE IF NOT EXISTS `course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `teachers_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `num_of_students` INT NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waitlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `waitlist` ;

CREATE TABLE IF NOT EXISTS `waitlist` (
  `waitlist_id` INT NOT NULL AUTO_INCREMENT,
  `capacity` CHAR(2) NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`waitlist_id`, `course`),
  UNIQUE INDEX `waitlist_id_UNIQUE` (`waitlist_id` ASC) VISIBLE,
  INDEX `fk_waitlist_course_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `fk_waitlist_course`
    FOREIGN KEY (`course`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule` ;

CREATE TABLE IF NOT EXISTS `schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(45) NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`schedule_id`, `course`),
  UNIQUE INDEX `schedule_id_UNIQUE` (`schedule_id` ASC) VISIBLE,
  INDEX `fk_schedule_course_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_course`
    FOREIGN KEY (`course`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `section` ;

CREATE TABLE IF NOT EXISTS `section` (
  `section_id` INT NOT NULL AUTO_INCREMENT,
  `semester_id` INT NOT NULL,
  `num_of_students` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`section_id`),
  UNIQUE INDEX `section_id_UNIQUE` (`section_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `semester` ;

CREATE TABLE IF NOT EXISTS `semester` (
  `semester_id` INT NOT NULL AUTO_INCREMENT,
  `term` VARCHAR(45) NOT NULL,
  `section` INT NOT NULL,
  PRIMARY KEY (`semester_id`),
  UNIQUE INDEX `semester_id_UNIQUE` (`semester_id` ASC) VISIBLE,
  INDEX `fk_semester_section_idx` (`section` ASC) VISIBLE,
  CONSTRAINT `fk_semester_section`
    FOREIGN KEY (`section`)
    REFERENCES `section` (`section_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `college`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `college` ;

CREATE TABLE IF NOT EXISTS `college` (
  `college_id` INT NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`college_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `register`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `register` ;

CREATE TABLE IF NOT EXISTS `register` (
  `student` INT NOT NULL,
  `semester` INT NOT NULL,
  INDEX `fk_register_semester_idx` (`semester` ASC) VISIBLE,
  INDEX `fk_register_student_idx` (`student` ASC) VISIBLE,
  CONSTRAINT `fk_register_student`
    FOREIGN KEY (`student`)
    REFERENCES `student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_register_semester`
    FOREIGN KEY (`semester`)
    REFERENCES `semester` (`semester_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attends` ;

CREATE TABLE IF NOT EXISTS `attends` (
  `student` INT NOT NULL,
  `college` INT NOT NULL,
  PRIMARY KEY (`student`, `college`),
  INDEX `fk_attends_college_idx` (`college` ASC) VISIBLE,
  CONSTRAINT `fk_attends_student`
    FOREIGN KEY (`student`)
    REFERENCES `student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_attends_college`
    FOREIGN KEY (`college`)
    REFERENCES `college` (`college_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `college_has`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `college_has` ;

CREATE TABLE IF NOT EXISTS `college_has` (
  `college` INT NOT NULL,
  `parkinglot` INT NOT NULL,
  `clubs` INT NOT NULL,
  `buildings` INT NOT NULL,
  INDEX `fk_college_has_clubs_idx` (`clubs` ASC) VISIBLE,
  INDEX `fk_college_has_buildings_idx` (`buildings` ASC) VISIBLE,
  INDEX `fk_college_has_college_idx` (`college` ASC) VISIBLE,
  PRIMARY KEY (`college`),
  CONSTRAINT `fk_college_has_clubs`
    FOREIGN KEY (`clubs`)
    REFERENCES `clubs` (`club_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_college_has_parkinglots`
    FOREIGN KEY (`parkinglot`)
    REFERENCES `parking lots` (`parkinglot_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_college_has_buildings`
    FOREIGN KEY (`buildings`)
    REFERENCES `buildings` (`building_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_college_has_college`
    FOREIGN KEY (`college`)
    REFERENCES `college` (`college_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employs` ;

CREATE TABLE IF NOT EXISTS `employs` (
  `college` INT NOT NULL,
  `faculty` INT NOT NULL,
  `staff` INT NOT NULL,
  INDEX `fk_employs_staff_idx` (`staff` ASC) VISIBLE,
  INDEX `fk_employs_college_idx` (`college` ASC) VISIBLE,
  CONSTRAINT `fk_employs_faculty`
    FOREIGN KEY (`faculty`)
    REFERENCES `faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employs_staff`
    FOREIGN KEY (`staff`)
    REFERENCES `staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employs_college`
    FOREIGN KEY (`college`)
    REFERENCES `college` (`college_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `college_offers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `college_offers` ;

CREATE TABLE IF NOT EXISTS `college_offers` (
  `college` INT NOT NULL,
  `degrees` INT NOT NULL,
  PRIMARY KEY (`college`),
  INDEX `fk_college_offers_degrees_idx` (`degrees` ASC) VISIBLE,
  CONSTRAINT `fk_college_offers_college`
    FOREIGN KEY (`college`)
    REFERENCES `college` (`college_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_college_offers_degrees`
    FOREIGN KEY (`degrees`)
    REFERENCES `degrees` (`degree_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graduates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graduates` ;

CREATE TABLE IF NOT EXISTS `graduates` (
  `degree` INT NOT NULL,
  `student` INT NOT NULL,
  INDEX `fk_graduates_student_idx` (`student` ASC) VISIBLE,
  CONSTRAINT `fk_graduates_degree`
    FOREIGN KEY (`degree`)
    REFERENCES `degrees` (`degree_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_graduates_student`
    FOREIGN KEY (`student`)
    REFERENCES `student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semester_contains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `semester_contains` ;

CREATE TABLE IF NOT EXISTS `semester_contains` (
  `semester` INT NOT NULL,
  `courses` INT NOT NULL,
  PRIMARY KEY (`semester`),
  INDEX `fk_semester_courses_idx` (`courses` ASC) VISIBLE,
  CONSTRAINT `fk_semester_contains_semester`
    FOREIGN KEY (`semester`)
    REFERENCES `semester` (`semester_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semester_courses`
    FOREIGN KEY (`courses`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildings_contain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildings_contain` ;

CREATE TABLE IF NOT EXISTS `buildings_contain` (
  `building` INT NOT NULL,
  `services` INT NOT NULL,
  `campuses` INT NOT NULL,
  `departments` INT NOT NULL,
  `offices` INT NOT NULL,
  PRIMARY KEY (`building`),
  INDEX `fk_buildings_contain_campuses_idx` (`campuses` ASC) VISIBLE,
  INDEX `fk_buildings_contain_departments_idx` (`departments` ASC) VISIBLE,
  INDEX `fk_buildings_contain_services_idx` (`services` ASC) VISIBLE,
  INDEX `fk_buildings_contain_offices_idx` (`offices` ASC) VISIBLE,
  CONSTRAINT `fk_buildings_contain_buildings`
    FOREIGN KEY (`building`)
    REFERENCES `buildings` (`building_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_buildings_contain_campuses`
    FOREIGN KEY (`campuses`)
    REFERENCES `campuses` (`campuses_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_buildings_contain_departments`
    FOREIGN KEY (`departments`)
    REFERENCES `department` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_buildings_contain_services`
    FOREIGN KEY (`services`)
    REFERENCES `services` (`services_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_buildings_contain_offices`
    FOREIGN KEY (`offices`)
    REFERENCES `office` (`office_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course_contains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course_contains` ;

CREATE TABLE IF NOT EXISTS `course_contains` (
  `course` INT NOT NULL,
  `subject` INT NOT NULL,
  PRIMARY KEY (`course`),
  INDEX `fk_course_contains_subject_idx` (`subject` ASC) VISIBLE,
  CONSTRAINT `fk_course_contains_course`
    FOREIGN KEY (`course`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_course_contains_subject`
    FOREIGN KEY (`subject`)
    REFERENCES `subjects` (`subject_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teaches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teaches` ;

CREATE TABLE IF NOT EXISTS `teaches` (
  `professor` INT NOT NULL,
  `lecturer` INT NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`course`),
  INDEX `fk_teaches_lecturer_idx` (`lecturer` ASC) VISIBLE,
  INDEX `fk_teaches_courses_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `fk_teaches_professor`
    FOREIGN KEY (`professor`)
    REFERENCES `professor` (`professor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_teaches_lecturer`
    FOREIGN KEY (`lecturer`)
    REFERENCES `lecturer` (`lecturer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_teaches_courses`
    FOREIGN KEY (`course`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- MySQL Script generated by MySQL Workbench
-- Thu Jul 22 22:28:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student` ;

CREATE TABLE IF NOT EXISTS `student` (
  `student_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faculty` ;

CREATE TABLE IF NOT EXISTS `faculty` (
  `faculty_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `salary` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`faculty_id`),
  UNIQUE INDEX `faculty_id_UNIQUE` (`faculty_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `advisor` ;

CREATE TABLE IF NOT EXISTS `advisor` (
  `advisor_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'Enter description of advisor',
  `faculty_id` INT NOT NULL,
  PRIMARY KEY (`advisor_id`),
  INDEX `fk_advisor_faculty_idx` (`faculty_id` ASC) VISIBLE,
  CONSTRAINT `fk_advisor_faculty`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researcher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researcher` ;

CREATE TABLE IF NOT EXISTS `researcher` (
  `researcher_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter description of researcher',
  `faculty_id` INT NOT NULL,
  PRIMARY KEY (`researcher_id`),
  UNIQUE INDEX `researcher_id_UNIQUE` (`researcher_id` ASC) VISIBLE,
  INDEX `fk_researcher_faculty_idx` (`faculty_id` ASC) VISIBLE,
  CONSTRAINT `fk_researcher_faculty`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `office` ;

CREATE TABLE IF NOT EXISTS `office` (
  `office_id` INT NOT NULL AUTO_INCREMENT,
  `room_num` CHAR(3) NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`office_id`),
  UNIQUE INDEX `office_id_UNIQUE` (`office_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lecturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecturer` ;

CREATE TABLE IF NOT EXISTS `lecturer` (
  `lecturer_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter description of lecturer',
  `faculty_id` INT NOT NULL,
  `office` INT NOT NULL,
  PRIMARY KEY (`lecturer_id`),
  UNIQUE INDEX `lecturer_id_UNIQUE` (`lecturer_id` ASC) VISIBLE,
  INDEX `fk_lecturer_faculty_idx` (`faculty_id` ASC) VISIBLE,
  INDEX `fk_lecturer_office_idx` (`office` ASC) VISIBLE,
  CONSTRAINT `fk_lecturer_faculty`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lecturer_office`
    FOREIGN KEY (`office`)
    REFERENCES `office` (`office_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `professor` ;

CREATE TABLE IF NOT EXISTS `professor` (
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter professors desciption here',
  `faculty_id` INT NOT NULL,
  `office` INT NOT NULL,
  PRIMARY KEY (`professor_id`),
  UNIQUE INDEX `professor_id_UNIQUE` (`professor_id` ASC) VISIBLE,
  INDEX `fk_professor_faculty_idx` (`faculty_id` ASC) VISIBLE,
  INDEX `fk_professor_office_idx` (`office` ASC) VISIBLE,
  CONSTRAINT `fk_professor_faculty`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_professor_office`
    FOREIGN KEY (`office`)
    REFERENCES `office` (`office_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chair` ;

CREATE TABLE IF NOT EXISTS `chair` (
  `chair_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter chair description here',
  `faculty_id` INT NOT NULL,
  `office` INT NOT NULL,
  PRIMARY KEY (`chair_id`),
  UNIQUE INDEX `chair_id_UNIQUE` (`chair_id` ASC) VISIBLE,
  INDEX `fk_chair_faculty_idx` (`faculty_id` ASC) VISIBLE,
  INDEX `fk_chair_office_idx` (`office` ASC) VISIBLE,
  CONSTRAINT `fk_chair_faculty`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chair_office`
    FOREIGN KEY (`office`)
    REFERENCES `office` (`office_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `staff` ;

CREATE TABLE IF NOT EXISTS `staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`staff_id`),
  UNIQUE INDEX `staff_id_UNIQUE` (`staff_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `custodian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custodian` ;

CREATE TABLE IF NOT EXISTS `custodian` (
  `custodian_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'custodian description',
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`custodian_id`),
  INDEX `fk_custodian_staff_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_custodian_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `librarian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `librarian` ;

CREATE TABLE IF NOT EXISTS `librarian` (
  `librarian_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter librarian description here',
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`librarian_id`),
  UNIQUE INDEX `librarian_id_UNIQUE` (`librarian_id` ASC) VISIBLE,
  INDEX `fk_librarian_staff_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_librarian_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food clerk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food clerk` ;

CREATE TABLE IF NOT EXISTS `food clerk` (
  `foodclerk_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter food clerk description here',
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`foodclerk_id`),
  UNIQUE INDEX `foodclerk_id_UNIQUE` (`foodclerk_id` ASC) VISIBLE,
  INDEX `fk_food clerk_staff_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_food clerk_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipment` ;

CREATE TABLE IF NOT EXISTS `equipment` (
  `equipment_id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(100) NOT NULL,
  `description` VARCHAR(150) NOT NULL DEFAULT 'enter equipment description',
  `staff` INT NOT NULL,
  PRIMARY KEY (`equipment_id`),
  UNIQUE INDEX `equipment_id_UNIQUE` (`equipment_id` ASC) VISIBLE,
  INDEX `fk_equipment_staff_idx` (`staff` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_staff`
    FOREIGN KEY (`staff`)
    REFERENCES `staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clubs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clubs` ;

CREATE TABLE IF NOT EXISTS `clubs` (
  `club_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `num_of_members` INT NOT NULL DEFAULT 0,
  `location` VARCHAR(100) NOT NULL,
  `website` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`club_id`),
  UNIQUE INDEX `club_id_UNIQUE` (`club_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parking lots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parking lots` ;

CREATE TABLE IF NOT EXISTS `parking lots` (
  `parkinglot_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`parkinglot_id`),
  UNIQUE INDEX `parkinglot_id_UNIQUE` (`parkinglot_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `department` ;

CREATE TABLE IF NOT EXISTS `department` (
  `department_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `office_location` VARCHAR(100) NOT NULL,
  `chair_id` INT NOT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildings` ;

CREATE TABLE IF NOT EXISTS `buildings` (
  `building_id` INT NOT NULL AUTO_INCREMENT,
  `capacity` INT NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`building_id`),
  UNIQUE INDEX `building_id_UNIQUE` (`building_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campuses` ;

CREATE TABLE IF NOT EXISTS `campuses` (
  `campuses_id` INT NOT NULL AUTO_INCREMENT,
  `roles` VARCHAR(45) NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`campuses_id`),
  UNIQUE INDEX `campuses_id_UNIQUE` (`campuses_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `subjects` ;

CREATE TABLE IF NOT EXISTS `subjects` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `total_subject_nums` INT NOT NULL,
  PRIMARY KEY (`subject_id`),
  UNIQUE INDEX `subject_id_UNIQUE` (`subject_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tutoring`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tutoring` ;

CREATE TABLE IF NOT EXISTS `tutoring` (
  `tutoring_id` INT NOT NULL AUTO_INCREMENT,
  `subject` INT NOT NULL,
  `staff_members` INT NOT NULL,
  PRIMARY KEY (`tutoring_id`),
  UNIQUE INDEX `tutoring_id_UNIQUE` (`tutoring_id` ASC) VISIBLE,
  INDEX `fk_tutoring_subject_idx` (`subject` ASC) VISIBLE,
  CONSTRAINT `fk_tutoring_subject`
    FOREIGN KEY (`subject`)
    REFERENCES `subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health and wellness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `health and wellness` ;

CREATE TABLE IF NOT EXISTS `health and wellness` (
  `health_and_wellness_id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(100) NOT NULL,
  `staff_members` INT NOT NULL,
  PRIMARY KEY (`health_and_wellness_id`),
  UNIQUE INDEX `health_and_wellness_id_UNIQUE` (`health_and_wellness_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `services` ;

CREATE TABLE IF NOT EXISTS `services` (
  `services_id` INT NOT NULL AUTO_INCREMENT,
  `staff_num` INT NOT NULL,
  `health and wellness` INT NOT NULL,
  `tutoring` INT NOT NULL,
  PRIMARY KEY (`services_id`),
  UNIQUE INDEX `services_id_UNIQUE` (`services_id` ASC) VISIBLE,
  INDEX `fk_services_healthandwell_idx` (`health and wellness` ASC) VISIBLE,
  INDEX `fk_services_tutoring_idx` (`tutoring` ASC) VISIBLE,
  CONSTRAINT `fk_services_tutoring`
    FOREIGN KEY (`tutoring`)
    REFERENCES `tutoring` (`tutoring_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_services_healthandwell`
    FOREIGN KEY (`health and wellness`)
    REFERENCES `health and wellness` (`health_and_wellness_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `degrees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `degrees` ;

CREATE TABLE IF NOT EXISTS `degrees` (
  `degree_id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(25) NOT NULL,
  `type` VARCHAR(25) NOT NULL,
  `description` VARCHAR(100) NOT NULL DEFAULT 'enter degree description',
  PRIMARY KEY (`degree_id`),
  UNIQUE INDEX `degree_id_UNIQUE` (`degree_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arts` ;

CREATE TABLE IF NOT EXISTS `arts` (
  `arts_id` INT NOT NULL AUTO_INCREMENT,
  `arts_subject_num` INT NOT NULL,
  `subject` INT NOT NULL,
  PRIMARY KEY (`arts_id`),
  UNIQUE INDEX `arts_id_UNIQUE` (`arts_id` ASC) VISIBLE,
  INDEX `fk_arts_subject_idx` (`subject` ASC) VISIBLE,
  CONSTRAINT `fk_arts_subject`
    FOREIGN KEY (`subject`)
    REFERENCES `subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sciences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sciences` ;

CREATE TABLE IF NOT EXISTS `sciences` (
  `sciences_id` INT NOT NULL AUTO_INCREMENT,
  `sciences_subject_num` INT NOT NULL,
  `subject` INT NOT NULL,
  PRIMARY KEY (`sciences_id`),
  UNIQUE INDEX `sciences_id_UNIQUE` (`sciences_id` ASC) VISIBLE,
  INDEX `fk_sciences_subject_idx` (`subject` ASC) VISIBLE,
  CONSTRAINT `fk_sciences_subject`
    FOREIGN KEY (`subject`)
    REFERENCES `subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `languages` ;

CREATE TABLE IF NOT EXISTS `languages` (
  `languages_id` INT NOT NULL AUTO_INCREMENT,
  `languages_subject_num` INT NOT NULL,
  `subject` INT NOT NULL,
  PRIMARY KEY (`languages_id`),
  UNIQUE INDEX `languages_id_UNIQUE` (`languages_id` ASC) VISIBLE,
  INDEX `fk_languages_subject_idx` (`subject` ASC) VISIBLE,
  CONSTRAINT `fk_languages_subject`
    FOREIGN KEY (`subject`)
    REFERENCES `subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course` ;

CREATE TABLE IF NOT EXISTS `course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `teachers_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `num_of_students` INT NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waitlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `waitlist` ;

CREATE TABLE IF NOT EXISTS `waitlist` (
  `waitlist_id` INT NOT NULL AUTO_INCREMENT,
  `capacity` CHAR(2) NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`waitlist_id`, `course`),
  UNIQUE INDEX `waitlist_id_UNIQUE` (`waitlist_id` ASC) VISIBLE,
  INDEX `fk_waitlist_course_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `fk_waitlist_course`
    FOREIGN KEY (`course`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule` ;

CREATE TABLE IF NOT EXISTS `schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(45) NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`schedule_id`, `course`),
  UNIQUE INDEX `schedule_id_UNIQUE` (`schedule_id` ASC) VISIBLE,
  INDEX `fk_schedule_course_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_course`
    FOREIGN KEY (`course`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `section` ;

CREATE TABLE IF NOT EXISTS `section` (
  `section_id` INT NOT NULL AUTO_INCREMENT,
  `semester_id` INT NOT NULL,
  `num_of_students` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`section_id`),
  UNIQUE INDEX `section_id_UNIQUE` (`section_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `semester` ;

CREATE TABLE IF NOT EXISTS `semester` (
  `semester_id` INT NOT NULL AUTO_INCREMENT,
  `term` VARCHAR(45) NOT NULL,
  `section` INT NOT NULL,
  PRIMARY KEY (`semester_id`),
  UNIQUE INDEX `semester_id_UNIQUE` (`semester_id` ASC) VISIBLE,
  INDEX `fk_semester_section_idx` (`section` ASC) VISIBLE,
  CONSTRAINT `fk_semester_section`
    FOREIGN KEY (`section`)
    REFERENCES `section` (`section_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `college`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `college` ;

CREATE TABLE IF NOT EXISTS `college` (
  `college_id` INT NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`college_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `register`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `register` ;

CREATE TABLE IF NOT EXISTS `register` (
  `student` INT NOT NULL,
  `semester` INT NOT NULL,
  INDEX `fk_register_semester_idx` (`semester` ASC) VISIBLE,
  INDEX `fk_register_student_idx` (`student` ASC) VISIBLE,
  CONSTRAINT `fk_register_student`
    FOREIGN KEY (`student`)
    REFERENCES `student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_register_semester`
    FOREIGN KEY (`semester`)
    REFERENCES `semester` (`semester_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attends` ;

CREATE TABLE IF NOT EXISTS `attends` (
  `student` INT NOT NULL,
  `college` INT NOT NULL,
  PRIMARY KEY (`student`, `college`),
  INDEX `fk_attends_college_idx` (`college` ASC) VISIBLE,
  CONSTRAINT `fk_attends_student`
    FOREIGN KEY (`student`)
    REFERENCES `student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_attends_college`
    FOREIGN KEY (`college`)
    REFERENCES `college` (`college_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `college_has`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `college_has` ;

CREATE TABLE IF NOT EXISTS `college_has` (
  `college` INT NOT NULL,
  `parkinglot` INT NOT NULL,
  `clubs` INT NOT NULL,
  `buildings` INT NOT NULL,
  INDEX `fk_college_has_clubs_idx` (`clubs` ASC) VISIBLE,
  INDEX `fk_college_has_buildings_idx` (`buildings` ASC) VISIBLE,
  INDEX `fk_college_has_college_idx` (`college` ASC) VISIBLE,
  PRIMARY KEY (`college`),
  CONSTRAINT `fk_college_has_clubs`
    FOREIGN KEY (`clubs`)
    REFERENCES `clubs` (`club_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_college_has_parkinglots`
    FOREIGN KEY (`parkinglot`)
    REFERENCES `parking lots` (`parkinglot_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_college_has_buildings`
    FOREIGN KEY (`buildings`)
    REFERENCES `buildings` (`building_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_college_has_college`
    FOREIGN KEY (`college`)
    REFERENCES `college` (`college_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employs` ;

CREATE TABLE IF NOT EXISTS `employs` (
  `college` INT NOT NULL,
  `faculty` INT NOT NULL,
  `staff` INT NOT NULL,
  INDEX `fk_employs_staff_idx` (`staff` ASC) VISIBLE,
  INDEX `fk_employs_college_idx` (`college` ASC) VISIBLE,
  CONSTRAINT `fk_employs_faculty`
    FOREIGN KEY (`faculty`)
    REFERENCES `faculty` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employs_staff`
    FOREIGN KEY (`staff`)
    REFERENCES `staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employs_college`
    FOREIGN KEY (`college`)
    REFERENCES `college` (`college_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `college_offers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `college_offers` ;

CREATE TABLE IF NOT EXISTS `college_offers` (
  `college` INT NOT NULL,
  `degrees` INT NOT NULL,
  PRIMARY KEY (`college`),
  INDEX `fk_college_offers_degrees_idx` (`degrees` ASC) VISIBLE,
  CONSTRAINT `fk_college_offers_college`
    FOREIGN KEY (`college`)
    REFERENCES `college` (`college_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_college_offers_degrees`
    FOREIGN KEY (`degrees`)
    REFERENCES `degrees` (`degree_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graduates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graduates` ;

CREATE TABLE IF NOT EXISTS `graduates` (
  `degree` INT NOT NULL,
  `student` INT NOT NULL,
  INDEX `fk_graduates_student_idx` (`student` ASC) VISIBLE,
  CONSTRAINT `fk_graduates_degree`
    FOREIGN KEY (`degree`)
    REFERENCES `degrees` (`degree_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_graduates_student`
    FOREIGN KEY (`student`)
    REFERENCES `student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semester_contains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `semester_contains` ;

CREATE TABLE IF NOT EXISTS `semester_contains` (
  `semester` INT NOT NULL,
  `courses` INT NOT NULL,
  PRIMARY KEY (`semester`),
  INDEX `fk_semester_courses_idx` (`courses` ASC) VISIBLE,
  CONSTRAINT `fk_semester_contains_semester`
    FOREIGN KEY (`semester`)
    REFERENCES `semester` (`semester_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semester_courses`
    FOREIGN KEY (`courses`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildings_contain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildings_contain` ;

CREATE TABLE IF NOT EXISTS `buildings_contain` (
  `building` INT NOT NULL,
  `services` INT NOT NULL,
  `campuses` INT NOT NULL,
  `departments` INT NOT NULL,
  `offices` INT NOT NULL,
  PRIMARY KEY (`building`),
  INDEX `fk_buildings_contain_campuses_idx` (`campuses` ASC) VISIBLE,
  INDEX `fk_buildings_contain_departments_idx` (`departments` ASC) VISIBLE,
  INDEX `fk_buildings_contain_services_idx` (`services` ASC) VISIBLE,
  INDEX `fk_buildings_contain_offices_idx` (`offices` ASC) VISIBLE,
  CONSTRAINT `fk_buildings_contain_buildings`
    FOREIGN KEY (`building`)
    REFERENCES `buildings` (`building_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_buildings_contain_campuses`
    FOREIGN KEY (`campuses`)
    REFERENCES `campuses` (`campuses_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_buildings_contain_departments`
    FOREIGN KEY (`departments`)
    REFERENCES `department` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_buildings_contain_services`
    FOREIGN KEY (`services`)
    REFERENCES `services` (`services_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_buildings_contain_offices`
    FOREIGN KEY (`offices`)
    REFERENCES `office` (`office_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course_contains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course_contains` ;

CREATE TABLE IF NOT EXISTS `course_contains` (
  `course` INT NOT NULL,
  `subject` INT NOT NULL,
  PRIMARY KEY (`course`),
  INDEX `fk_course_contains_subject_idx` (`subject` ASC) VISIBLE,
  CONSTRAINT `fk_course_contains_course`
    FOREIGN KEY (`course`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_course_contains_subject`
    FOREIGN KEY (`subject`)
    REFERENCES `subjects` (`subject_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teaches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teaches` ;

CREATE TABLE IF NOT EXISTS `teaches` (
  `professor` INT NOT NULL,
  `lecturer` INT NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`course`),
  INDEX `fk_teaches_lecturer_idx` (`lecturer` ASC) VISIBLE,
  INDEX `fk_teaches_courses_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `fk_teaches_professor`
    FOREIGN KEY (`professor`)
    REFERENCES `professor` (`professor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_teaches_lecturer`
    FOREIGN KEY (`lecturer`)
    REFERENCES `lecturer` (`lecturer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_teaches_courses`
    FOREIGN KEY (`course`)
    REFERENCES `course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

DELIMITER $$
CREATE TRIGGER updateStaff_low AFTER UPDATE ON collegedb.`health and wellness` FOR EACH ROW
	BEGIN
		IF (OLD.staff_members > NEW.staff_members) THEN
			UPDATE services
            SET services.staff_num = services.staff_num - NEW.staff_members
            WHERE `health and wellness` = NEW.health_and_wellness_id;
		END IF;
END;

DELIMITER $$$
CREATE TRIGGER updateStaff_high AFTER UPDATE ON collegedb.`health and wellness` FOR EACH ROW
	BEGIN
		IF (OLD.staff_members < NEW.staff_members) THEN
			UPDATE services
            SET services.staff_num = services.staff_num + NEW.staff_members
            WHERE `health and wellness` = NEW.health_and_wellness_id;
		END IF;
END;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
